name: Dependabot Auto-Merge

# Automatically approve and merge safe Dependabot PRs
# - Security updates: Always merge
# - Dev dependencies: Always merge
# - Patch/minor updates: Always merge
# - Major updates: Require manual review

on:
  pull_request:
    types: [opened]

concurrency:
  group: dependabot-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write
  issues: write
  checks: read

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    # Only run for Dependabot PRs
    if: github.actor == 'dependabot[bot]'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Determine if PR should auto-merge
        id: decision
        run: |
          echo "PR Title: ${{ github.event.pull_request.title }}"
          echo "Update type: ${{ steps.metadata.outputs.update-type }}"
          echo "Dependency names: ${{ steps.metadata.outputs.dependency-names }}"

          # Always merge security updates
          if [[ "${{ steps.metadata.outputs.update-type }}" == "version-update:semver-patch" ]] || \
             [[ "${{ steps.metadata.outputs.update-type }}" == "version-update:semver-minor" ]]; then
            echo "should_merge=true" >> $GITHUB_OUTPUT
            echo "reason=Patch/minor version update" >> $GITHUB_OUTPUT
          # Always merge dev dependencies
          elif echo "${{ steps.metadata.outputs.dependency-names }}" | grep -qE "@types/|eslint|prettier|typescript|@typescript-eslint"; then
            echo "should_merge=true" >> $GITHUB_OUTPUT
            echo "reason=Dev dependency" >> $GITHUB_OUTPUT
          # Skip major version bumps
          elif [[ "${{ steps.metadata.outputs.update-type }}" == "version-update:semver-major" ]]; then
            echo "should_merge=false" >> $GITHUB_OUTPUT
            echo "reason=Major version update - requires manual review" >> $GITHUB_OUTPUT
          else
            echo "should_merge=true" >> $GITHUB_OUTPUT
            echo "reason=Safe dependency update" >> $GITHUB_OUTPUT
          fi

      - name: Approve PR
        if: steps.decision.outputs.should_merge == 'true'
        run: |
          gh pr review "${{ github.event.pull_request.number }}" --approve --body "Auto-approved by Dependabot workflow: ${{ steps.decision.outputs.reason }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge
        if: steps.decision.outputs.should_merge == 'true'
        run: |
          gh pr merge "${{ github.event.pull_request.number }}" --auto --squash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment on major version PR
        if: steps.decision.outputs.should_merge == 'false'
        run: |
          gh pr comment "${{ github.event.pull_request.number }}" --body "**Manual review required** - This PR contains a major version update which may include breaking changes. Please review the changelog and test locally before merging."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
